version: '2'
services:
  logspout:
    image: gliderlabs/logspout:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:80"
  app:
    build: .
    volumes:
      - ./project:/scylla
    env_file:
      - ./secret.env
    ports:
      - "8080:8080"
      - "3449:3449"
      - "4096:4096"
  datomic:
    build: ./datomic
    ports:
      - "4336:4336"
      - "4335:4335"
      - "4334:4334"
    volumes:
      - ./datomic/data:/opt/datomic-pro-0.9.5359/data
  datomic-console:
    build:
      context: ./datomic
      dockerfile: Dockerfile.console
    ports:
      - "9000:9000"
