FROM gliderlabs/alpine:3.3
RUN apk add --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ inotify-tools sassc
COPY ./project/resources/scss /in
COPY ./project/resources/public/css /out
COPY ./script/compile-scss /opt/bin/run
CMD /opt/bin/run
